<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!--
Generated by IDEA
User: Badr Eddine
-->
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Wubba Dub Admin Page</title>
<link rel="stylesheet" type="text/css" href="style.css">
<style>
	*{
		font-family: Montserrat, serif;
	}
	.admin-btn{
		padding: 10px;
		font-size: 15px;
		color: white;
		background: #F24638;
		border: none;
		border-radius: 5px;
		cursor: pointer;
	}
	.admin-btn:hover{
		background: #ef1212;
	}
</style>
</head>
<body>

	<div class="admin-signup-header" >
	 	<h2> Admin Login</h2>
	</div>

	<form method="post" action="${pageContext.request.contextPath}/admin">
	 
	 	<input type="hidden" name="page" value="admin-login-form">
	 
	 	<!-- Display Validations errors -->
	 	<span style="color: #F24638; "><c:out value="${msg }"></c:out></span>
	 
	 	<div class="signup-group">
	 		<label>Username</label>
	 		<input type="text" name="username" placeholder="Your Username" value="<c:out value="${username }"></c:out>">
	 	</div>
	 	<div class="signup-group">
	 		<label>Password</label>
	 		<input type="password" name="password" placeholder="Enter password">
	 	</div>
	 	<div class="signup-group">
	 		<button type="submit" name="login" class="admin-btn">Log in</button>
	 	</div>
	 </form>
</body>
</html>